### ISSUE TITLE
Tensorflow Error causing model to fail on predict

### ISSUE THREAD

**Issue by ajbozarth** [IBM/MAX-Review-Text-Generator#4]
@ptitzler and I are both consistent;t getting the following error on prediction:

```
[2018-07-27 22:57:58,333] ERROR in app: Exception on /model/predict [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 101, in wrapper
    resp = f(*args, **kwargs)
  File "/workspace/api/model.py", line 56, in post
    generated_text = self.model_wrapper.predict(seed_text, gen_chars)
  File "/workspace/core/backend.py", line 84, in predict
    preds = self.model.predict(x, verbose=0)[0]
  File "/usr/local/lib/python3.6/site-packages/keras/models.py", line 1025, in predict
    steps=steps)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1839, in predict
    self._make_predict_function()
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1029, in _make_predict_function
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2499, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2442, in __init__
    with tf.control_dependencies(self.outputs):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4604, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 4310, in control_dependencies
    c = self.as_graph_element(c)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3323, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3402, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("activation_1/Softmax:0", shape=(?, 61), dtype=float32) is not an element of this graph.
```

**Comment by ajbozarth** [comment]
@MLnick this seems like something we should fix fast

**Comment by MLnick** [comment]
I confirm I get the same error. Strangely, it actually seems related to the Flask version (not Flask-restplus but underlying Flask).

Flask >= `1.0` gives the error, but running with Flask `0.12.4` works.

Digging deeper...

**Comment by MLnick** [comment]
It seems to be related to the way threading or context handling works (not sure exactly what changed). Fixing the TF Graph scoping fixes the issue and I will post a PR shortly.

Will also post a separate PR addressing pip requirements installation and freezing the dependency versions as per https://github.ibm.com/CODAIT/Usability-Enhancement/issues/8

**Comment by feihugis** [comment]
[This issue](https://github.com/keras-team/keras/issues/2397) in TensorFlow discussed a similar problem we met.
